/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 36
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LPAREN_STAR = 1,
  aux_sym_comment_token1 = 2,
  anon_sym_STAR_RPAREN = 3,
  anon_sym_DELAY = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  anon_sym_SCRIPT = 7,
  anon_sym_SERIAL_DEVICE = 8,
  anon_sym_INPUT_FILE = 9,
  anon_sym_OUTPUT_FILE = 10,
  anon_sym_SEND = 11,
  anon_sym_SEND_FILE = 12,
  anon_sym_STOP = 13,
  sym_delay_args = 14,
  anon_sym_SHIFT = 15,
  anon_sym_CARET = 16,
  anon_sym_GUI = 17,
  anon_sym_CTRL = 18,
  anon_sym_ALT = 19,
  sym_lowercase_key = 20,
  anon_sym_FN = 21,
  aux_sym_fn_key_token1 = 22,
  anon_sym_SPACE = 23,
  anon_sym__ = 24,
  anon_sym_UP = 25,
  anon_sym_DOWN = 26,
  anon_sym_LEFT = 27,
  anon_sym_RIGHT = 28,
  anon_sym_TAB = 29,
  anon_sym_ESC = 30,
  anon_sym_BACKSPACE = 31,
  anon_sym_ENTER = 32,
  anon_sym_SAVE = 33,
  sym_source_file = 34,
  sym_comment = 35,
  sym_command = 36,
  sym_generic_args = 37,
  sym_script = 38,
  sym_action = 39,
  sym_report = 40,
  sym_modifier_key = 41,
  sym_key_click = 42,
  sym_fn_key = 43,
  sym_special_key = 44,
  sym_macro = 45,
  aux_sym_source_file_repeat1 = 46,
  aux_sym_generic_args_repeat1 = 47,
  aux_sym_script_repeat1 = 48,
  aux_sym_report_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN_STAR] = "(*",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_STAR_RPAREN] = "*)",
  [anon_sym_DELAY] = "DELAY",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_SCRIPT] = "SCRIPT",
  [anon_sym_SERIAL_DEVICE] = "SERIAL_DEVICE",
  [anon_sym_INPUT_FILE] = "INPUT_FILE",
  [anon_sym_OUTPUT_FILE] = "OUTPUT_FILE",
  [anon_sym_SEND] = "SEND",
  [anon_sym_SEND_FILE] = "SEND_FILE",
  [anon_sym_STOP] = "STOP",
  [sym_delay_args] = "delay_args",
  [anon_sym_SHIFT] = "SHIFT",
  [anon_sym_CARET] = "^",
  [anon_sym_GUI] = "GUI",
  [anon_sym_CTRL] = "CTRL",
  [anon_sym_ALT] = "ALT",
  [sym_lowercase_key] = "lowercase_key",
  [anon_sym_FN] = "FN",
  [aux_sym_fn_key_token1] = "fn_key_token1",
  [anon_sym_SPACE] = "SPACE",
  [anon_sym__] = "_",
  [anon_sym_UP] = "UP",
  [anon_sym_DOWN] = "DOWN",
  [anon_sym_LEFT] = "LEFT",
  [anon_sym_RIGHT] = "RIGHT",
  [anon_sym_TAB] = "TAB",
  [anon_sym_ESC] = "ESC",
  [anon_sym_BACKSPACE] = "BACKSPACE",
  [anon_sym_ENTER] = "ENTER",
  [anon_sym_SAVE] = "SAVE",
  [sym_source_file] = "source_file",
  [sym_comment] = "comment",
  [sym_command] = "command",
  [sym_generic_args] = "generic_args",
  [sym_script] = "script",
  [sym_action] = "action",
  [sym_report] = "report",
  [sym_modifier_key] = "modifier_key",
  [sym_key_click] = "key_click",
  [sym_fn_key] = "fn_key",
  [sym_special_key] = "special_key",
  [sym_macro] = "macro",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_generic_args_repeat1] = "generic_args_repeat1",
  [aux_sym_script_repeat1] = "script_repeat1",
  [aux_sym_report_repeat1] = "report_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN_STAR] = anon_sym_LPAREN_STAR,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_STAR_RPAREN] = anon_sym_STAR_RPAREN,
  [anon_sym_DELAY] = anon_sym_DELAY,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_SCRIPT] = anon_sym_SCRIPT,
  [anon_sym_SERIAL_DEVICE] = anon_sym_SERIAL_DEVICE,
  [anon_sym_INPUT_FILE] = anon_sym_INPUT_FILE,
  [anon_sym_OUTPUT_FILE] = anon_sym_OUTPUT_FILE,
  [anon_sym_SEND] = anon_sym_SEND,
  [anon_sym_SEND_FILE] = anon_sym_SEND_FILE,
  [anon_sym_STOP] = anon_sym_STOP,
  [sym_delay_args] = sym_delay_args,
  [anon_sym_SHIFT] = anon_sym_SHIFT,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_GUI] = anon_sym_GUI,
  [anon_sym_CTRL] = anon_sym_CTRL,
  [anon_sym_ALT] = anon_sym_ALT,
  [sym_lowercase_key] = sym_lowercase_key,
  [anon_sym_FN] = anon_sym_FN,
  [aux_sym_fn_key_token1] = aux_sym_fn_key_token1,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym__] = anon_sym__,
  [anon_sym_UP] = anon_sym_UP,
  [anon_sym_DOWN] = anon_sym_DOWN,
  [anon_sym_LEFT] = anon_sym_LEFT,
  [anon_sym_RIGHT] = anon_sym_RIGHT,
  [anon_sym_TAB] = anon_sym_TAB,
  [anon_sym_ESC] = anon_sym_ESC,
  [anon_sym_BACKSPACE] = anon_sym_BACKSPACE,
  [anon_sym_ENTER] = anon_sym_ENTER,
  [anon_sym_SAVE] = anon_sym_SAVE,
  [sym_source_file] = sym_source_file,
  [sym_comment] = sym_comment,
  [sym_command] = sym_command,
  [sym_generic_args] = sym_generic_args,
  [sym_script] = sym_script,
  [sym_action] = sym_action,
  [sym_report] = sym_report,
  [sym_modifier_key] = sym_modifier_key,
  [sym_key_click] = sym_key_click,
  [sym_fn_key] = sym_fn_key,
  [sym_special_key] = sym_special_key,
  [sym_macro] = sym_macro,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_generic_args_repeat1] = aux_sym_generic_args_repeat1,
  [aux_sym_script_repeat1] = aux_sym_script_repeat1,
  [aux_sym_report_repeat1] = aux_sym_report_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DELAY] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SCRIPT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SERIAL_DEVICE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_INPUT_FILE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OUTPUT_FILE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEND_FILE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STOP] = {
    .visible = true,
    .named = false,
  },
  [sym_delay_args] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SHIFT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GUI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CTRL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ALT] = {
    .visible = true,
    .named = false,
  },
  [sym_lowercase_key] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_FN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_fn_key_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_UP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOWN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LEFT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RIGHT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TAB] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ESC] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BACKSPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ENTER] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SAVE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_args] = {
    .visible = true,
    .named = true,
  },
  [sym_script] = {
    .visible = true,
    .named = true,
  },
  [sym_action] = {
    .visible = true,
    .named = true,
  },
  [sym_report] = {
    .visible = true,
    .named = true,
  },
  [sym_modifier_key] = {
    .visible = true,
    .named = true,
  },
  [sym_key_click] = {
    .visible = true,
    .named = true,
  },
  [sym_fn_key] = {
    .visible = true,
    .named = true,
  },
  [sym_special_key] = {
    .visible = true,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_generic_args_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_script_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_report_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(93);
      ADVANCE_MAP(
        '(', 100,
        ')', 101,
        '*', 2,
        'A', 48,
        'B', 4,
        'C', 70,
        'D', 27,
        'E', 58,
        'F', 54,
        'G', 80,
        'I', 57,
        'L', 19,
        'O', 81,
        'R', 37,
        'S', 5,
        'T', 6,
        'U', 60,
        '^', 111,
        '_', 120,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(109);
      if (lookahead == ',' ||
          lookahead == '.' ||
          lookahead == '/' ||
          lookahead == ';' ||
          lookahead == '=' ||
          ('[' <= lookahead && lookahead <= ']') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0xa7) ADVANCE(115);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(99);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(109);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(97);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(94);
      END_STATE();
    case 4:
      if (lookahead == 'A') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == 'A') ADVANCE(84);
      if (lookahead == 'C') ADVANCE(68);
      if (lookahead == 'E') ADVANCE(55);
      if (lookahead == 'H') ADVANCE(42);
      if (lookahead == 'P') ADVANCE(8);
      if (lookahead == 'T') ADVANCE(59);
      END_STATE();
    case 6:
      if (lookahead == 'A') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'A') ADVANCE(87);
      END_STATE();
    case 8:
      if (lookahead == 'A') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'A') ADVANCE(49);
      END_STATE();
    case 10:
      if (lookahead == 'A') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 'B') ADVANCE(125);
      END_STATE();
    case 12:
      if (lookahead == 'C') ADVANCE(46);
      END_STATE();
    case 13:
      if (lookahead == 'C') ADVANCE(126);
      END_STATE();
    case 14:
      if (lookahead == 'C') ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == 'C') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 'C') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 'D') ADVANCE(106);
      END_STATE();
    case 18:
      if (lookahead == 'D') ADVANCE(28);
      END_STATE();
    case 19:
      if (lookahead == 'E') ADVANCE(30);
      END_STATE();
    case 20:
      if (lookahead == 'E') ADVANCE(129);
      END_STATE();
    case 21:
      if (lookahead == 'E') ADVANCE(119);
      END_STATE();
    case 22:
      if (lookahead == 'E') ADVANCE(127);
      END_STATE();
    case 23:
      if (lookahead == 'E') ADVANCE(107);
      END_STATE();
    case 24:
      if (lookahead == 'E') ADVANCE(104);
      END_STATE();
    case 25:
      if (lookahead == 'E') ADVANCE(105);
      END_STATE();
    case 26:
      if (lookahead == 'E') ADVANCE(103);
      END_STATE();
    case 27:
      if (lookahead == 'E') ADVANCE(50);
      if (lookahead == 'O') ADVANCE(86);
      END_STATE();
    case 28:
      if (lookahead == 'E') ADVANCE(85);
      END_STATE();
    case 29:
      if (lookahead == 'E') ADVANCE(66);
      END_STATE();
    case 30:
      if (lookahead == 'F') ADVANCE(72);
      END_STATE();
    case 31:
      if (lookahead == 'F') ADVANCE(41);
      END_STATE();
    case 32:
      if (lookahead == 'F') ADVANCE(75);
      END_STATE();
    case 33:
      if (lookahead == 'F') ADVANCE(43);
      END_STATE();
    case 34:
      if (lookahead == 'F') ADVANCE(45);
      END_STATE();
    case 35:
      if (lookahead == 'G') ADVANCE(36);
      END_STATE();
    case 36:
      if (lookahead == 'H') ADVANCE(74);
      END_STATE();
    case 37:
      if (lookahead == 'I') ADVANCE(35);
      END_STATE();
    case 38:
      if (lookahead == 'I') ADVANCE(112);
      END_STATE();
    case 39:
      if (lookahead == 'I') ADVANCE(9);
      END_STATE();
    case 40:
      if (lookahead == 'I') ADVANCE(62);
      END_STATE();
    case 41:
      if (lookahead == 'I') ADVANCE(51);
      END_STATE();
    case 42:
      if (lookahead == 'I') ADVANCE(32);
      END_STATE();
    case 43:
      if (lookahead == 'I') ADVANCE(52);
      END_STATE();
    case 44:
      if (lookahead == 'I') ADVANCE(16);
      END_STATE();
    case 45:
      if (lookahead == 'I') ADVANCE(53);
      END_STATE();
    case 46:
      if (lookahead == 'K') ADVANCE(69);
      END_STATE();
    case 47:
      if (lookahead == 'L') ADVANCE(113);
      END_STATE();
    case 48:
      if (lookahead == 'L') ADVANCE(71);
      END_STATE();
    case 49:
      if (lookahead == 'L') ADVANCE(88);
      END_STATE();
    case 50:
      if (lookahead == 'L') ADVANCE(7);
      END_STATE();
    case 51:
      if (lookahead == 'L') ADVANCE(23);
      END_STATE();
    case 52:
      if (lookahead == 'L') ADVANCE(24);
      END_STATE();
    case 53:
      if (lookahead == 'L') ADVANCE(25);
      END_STATE();
    case 54:
      if (lookahead == 'N') ADVANCE(116);
      END_STATE();
    case 55:
      if (lookahead == 'N') ADVANCE(17);
      if (lookahead == 'R') ADVANCE(39);
      END_STATE();
    case 56:
      if (lookahead == 'N') ADVANCE(122);
      END_STATE();
    case 57:
      if (lookahead == 'N') ADVANCE(63);
      END_STATE();
    case 58:
      if (lookahead == 'N') ADVANCE(77);
      if (lookahead == 'S') ADVANCE(13);
      END_STATE();
    case 59:
      if (lookahead == 'O') ADVANCE(61);
      END_STATE();
    case 60:
      if (lookahead == 'P') ADVANCE(121);
      END_STATE();
    case 61:
      if (lookahead == 'P') ADVANCE(108);
      END_STATE();
    case 62:
      if (lookahead == 'P') ADVANCE(76);
      END_STATE();
    case 63:
      if (lookahead == 'P') ADVANCE(82);
      END_STATE();
    case 64:
      if (lookahead == 'P') ADVANCE(10);
      END_STATE();
    case 65:
      if (lookahead == 'P') ADVANCE(83);
      END_STATE();
    case 66:
      if (lookahead == 'R') ADVANCE(128);
      END_STATE();
    case 67:
      if (lookahead == 'R') ADVANCE(47);
      END_STATE();
    case 68:
      if (lookahead == 'R') ADVANCE(40);
      END_STATE();
    case 69:
      if (lookahead == 'S') ADVANCE(64);
      END_STATE();
    case 70:
      if (lookahead == 'T') ADVANCE(67);
      END_STATE();
    case 71:
      if (lookahead == 'T') ADVANCE(114);
      END_STATE();
    case 72:
      if (lookahead == 'T') ADVANCE(123);
      END_STATE();
    case 73:
      if (lookahead == 'T') ADVANCE(89);
      END_STATE();
    case 74:
      if (lookahead == 'T') ADVANCE(124);
      END_STATE();
    case 75:
      if (lookahead == 'T') ADVANCE(110);
      END_STATE();
    case 76:
      if (lookahead == 'T') ADVANCE(102);
      END_STATE();
    case 77:
      if (lookahead == 'T') ADVANCE(29);
      END_STATE();
    case 78:
      if (lookahead == 'T') ADVANCE(90);
      END_STATE();
    case 79:
      if (lookahead == 'T') ADVANCE(65);
      END_STATE();
    case 80:
      if (lookahead == 'U') ADVANCE(38);
      END_STATE();
    case 81:
      if (lookahead == 'U') ADVANCE(79);
      END_STATE();
    case 82:
      if (lookahead == 'U') ADVANCE(73);
      END_STATE();
    case 83:
      if (lookahead == 'U') ADVANCE(78);
      END_STATE();
    case 84:
      if (lookahead == 'V') ADVANCE(20);
      END_STATE();
    case 85:
      if (lookahead == 'V') ADVANCE(44);
      END_STATE();
    case 86:
      if (lookahead == 'W') ADVANCE(56);
      END_STATE();
    case 87:
      if (lookahead == 'Y') ADVANCE(98);
      END_STATE();
    case 88:
      if (lookahead == '_') ADVANCE(18);
      END_STATE();
    case 89:
      if (lookahead == '_') ADVANCE(33);
      END_STATE();
    case 90:
      if (lookahead == '_') ADVANCE(34);
      END_STATE();
    case 91:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(91);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(118);
      END_STATE();
    case 92:
      if (eof) ADVANCE(93);
      ADVANCE_MAP(
        '(', 3,
        ')', 101,
        'A', 48,
        'B', 4,
        'C', 70,
        'D', 27,
        'E', 58,
        'F', 54,
        'G', 80,
        'I', 57,
        'L', 19,
        'O', 81,
        'R', 37,
        'S', 5,
        'T', 6,
        'U', 60,
        '^', 111,
        '_', 120,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(92);
      if (lookahead == ',' ||
          ('.' <= lookahead && lookahead <= '9') ||
          lookahead == ';' ||
          lookahead == '=' ||
          ('[' <= lookahead && lookahead <= ']') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0xa7) ADVANCE(115);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_LPAREN_STAR);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(95);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(96);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(96);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_STAR_RPAREN);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_DELAY);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == '*') ADVANCE(94);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_SCRIPT);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_SERIAL_DEVICE);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_INPUT_FILE);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_OUTPUT_FILE);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_SEND);
      if (lookahead == '_') ADVANCE(31);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_SEND_FILE);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_STOP);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_delay_args);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(109);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_SHIFT);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_GUI);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_CTRL);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_ALT);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_lowercase_key);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_FN);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(aux_sym_fn_key_token1);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(aux_sym_fn_key_token1);
      if (('0' <= lookahead && lookahead <= '2')) ADVANCE(117);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_SPACE);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_UP);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_DOWN);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_LEFT);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_RIGHT);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_TAB);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_ESC);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_BACKSPACE);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_ENTER);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_SAVE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 92},
  [2] = {.lex_state = 92},
  [3] = {.lex_state = 92},
  [4] = {.lex_state = 92},
  [5] = {.lex_state = 92},
  [6] = {.lex_state = 92},
  [7] = {.lex_state = 92},
  [8] = {.lex_state = 92},
  [9] = {.lex_state = 92},
  [10] = {.lex_state = 92},
  [11] = {.lex_state = 92},
  [12] = {.lex_state = 92},
  [13] = {.lex_state = 92},
  [14] = {.lex_state = 92},
  [15] = {.lex_state = 92},
  [16] = {.lex_state = 92},
  [17] = {.lex_state = 92},
  [18] = {.lex_state = 92},
  [19] = {.lex_state = 92},
  [20] = {.lex_state = 92},
  [21] = {.lex_state = 92},
  [22] = {.lex_state = 92},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 95},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 91},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN_STAR] = ACTIONS(1),
    [anon_sym_STAR_RPAREN] = ACTIONS(1),
    [anon_sym_DELAY] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_SCRIPT] = ACTIONS(1),
    [anon_sym_SERIAL_DEVICE] = ACTIONS(1),
    [anon_sym_INPUT_FILE] = ACTIONS(1),
    [anon_sym_OUTPUT_FILE] = ACTIONS(1),
    [anon_sym_SEND] = ACTIONS(1),
    [anon_sym_SEND_FILE] = ACTIONS(1),
    [anon_sym_STOP] = ACTIONS(1),
    [sym_delay_args] = ACTIONS(1),
    [anon_sym_SHIFT] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_GUI] = ACTIONS(1),
    [anon_sym_CTRL] = ACTIONS(1),
    [anon_sym_ALT] = ACTIONS(1),
    [sym_lowercase_key] = ACTIONS(1),
    [anon_sym_FN] = ACTIONS(1),
    [anon_sym_SPACE] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_UP] = ACTIONS(1),
    [anon_sym_DOWN] = ACTIONS(1),
    [anon_sym_LEFT] = ACTIONS(1),
    [anon_sym_RIGHT] = ACTIONS(1),
    [anon_sym_TAB] = ACTIONS(1),
    [anon_sym_ESC] = ACTIONS(1),
    [anon_sym_BACKSPACE] = ACTIONS(1),
    [anon_sym_ENTER] = ACTIONS(1),
    [anon_sym_SAVE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(28),
    [sym_comment] = STATE(16),
    [sym_command] = STATE(16),
    [aux_sym_source_file_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LPAREN_STAR] = ACTIONS(5),
    [anon_sym_DELAY] = ACTIONS(7),
    [anon_sym_SCRIPT] = ACTIONS(9),
    [anon_sym_SERIAL_DEVICE] = ACTIONS(11),
    [anon_sym_INPUT_FILE] = ACTIONS(11),
    [anon_sym_OUTPUT_FILE] = ACTIONS(11),
    [anon_sym_SEND] = ACTIONS(13),
    [anon_sym_SEND_FILE] = ACTIONS(15),
    [anon_sym_STOP] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym_script] = STATE(33),
    [sym_action] = STATE(3),
    [sym_report] = STATE(10),
    [sym_modifier_key] = STATE(5),
    [sym_key_click] = STATE(8),
    [sym_fn_key] = STATE(7),
    [sym_special_key] = STATE(7),
    [sym_macro] = STATE(10),
    [aux_sym_script_repeat1] = STATE(3),
    [aux_sym_report_repeat1] = STATE(5),
    [anon_sym_SERIAL_DEVICE] = ACTIONS(17),
    [anon_sym_SHIFT] = ACTIONS(19),
    [anon_sym_CARET] = ACTIONS(19),
    [anon_sym_GUI] = ACTIONS(19),
    [anon_sym_CTRL] = ACTIONS(19),
    [anon_sym_ALT] = ACTIONS(19),
    [sym_lowercase_key] = ACTIONS(21),
    [anon_sym_FN] = ACTIONS(23),
    [anon_sym_SPACE] = ACTIONS(25),
    [anon_sym__] = ACTIONS(25),
    [anon_sym_UP] = ACTIONS(25),
    [anon_sym_DOWN] = ACTIONS(25),
    [anon_sym_LEFT] = ACTIONS(25),
    [anon_sym_RIGHT] = ACTIONS(25),
    [anon_sym_TAB] = ACTIONS(25),
    [anon_sym_ESC] = ACTIONS(25),
    [anon_sym_BACKSPACE] = ACTIONS(25),
    [anon_sym_ENTER] = ACTIONS(25),
    [anon_sym_SAVE] = ACTIONS(17),
  },
  [STATE(3)] = {
    [sym_action] = STATE(4),
    [sym_report] = STATE(10),
    [sym_modifier_key] = STATE(5),
    [sym_key_click] = STATE(8),
    [sym_fn_key] = STATE(7),
    [sym_special_key] = STATE(7),
    [sym_macro] = STATE(10),
    [aux_sym_script_repeat1] = STATE(4),
    [aux_sym_report_repeat1] = STATE(5),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_SERIAL_DEVICE] = ACTIONS(17),
    [anon_sym_SHIFT] = ACTIONS(19),
    [anon_sym_CARET] = ACTIONS(19),
    [anon_sym_GUI] = ACTIONS(19),
    [anon_sym_CTRL] = ACTIONS(19),
    [anon_sym_ALT] = ACTIONS(19),
    [sym_lowercase_key] = ACTIONS(21),
    [anon_sym_FN] = ACTIONS(23),
    [anon_sym_SPACE] = ACTIONS(25),
    [anon_sym__] = ACTIONS(25),
    [anon_sym_UP] = ACTIONS(25),
    [anon_sym_DOWN] = ACTIONS(25),
    [anon_sym_LEFT] = ACTIONS(25),
    [anon_sym_RIGHT] = ACTIONS(25),
    [anon_sym_TAB] = ACTIONS(25),
    [anon_sym_ESC] = ACTIONS(25),
    [anon_sym_BACKSPACE] = ACTIONS(25),
    [anon_sym_ENTER] = ACTIONS(25),
    [anon_sym_SAVE] = ACTIONS(17),
  },
  [STATE(4)] = {
    [sym_action] = STATE(4),
    [sym_report] = STATE(10),
    [sym_modifier_key] = STATE(5),
    [sym_key_click] = STATE(8),
    [sym_fn_key] = STATE(7),
    [sym_special_key] = STATE(7),
    [sym_macro] = STATE(10),
    [aux_sym_script_repeat1] = STATE(4),
    [aux_sym_report_repeat1] = STATE(5),
    [anon_sym_RPAREN] = ACTIONS(29),
    [anon_sym_SERIAL_DEVICE] = ACTIONS(31),
    [anon_sym_SHIFT] = ACTIONS(34),
    [anon_sym_CARET] = ACTIONS(34),
    [anon_sym_GUI] = ACTIONS(34),
    [anon_sym_CTRL] = ACTIONS(34),
    [anon_sym_ALT] = ACTIONS(34),
    [sym_lowercase_key] = ACTIONS(37),
    [anon_sym_FN] = ACTIONS(40),
    [anon_sym_SPACE] = ACTIONS(43),
    [anon_sym__] = ACTIONS(43),
    [anon_sym_UP] = ACTIONS(43),
    [anon_sym_DOWN] = ACTIONS(43),
    [anon_sym_LEFT] = ACTIONS(43),
    [anon_sym_RIGHT] = ACTIONS(43),
    [anon_sym_TAB] = ACTIONS(43),
    [anon_sym_ESC] = ACTIONS(43),
    [anon_sym_BACKSPACE] = ACTIONS(43),
    [anon_sym_ENTER] = ACTIONS(43),
    [anon_sym_SAVE] = ACTIONS(31),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(21), 1,
      sym_lowercase_key,
    ACTIONS(23), 1,
      anon_sym_FN,
    STATE(11), 1,
      sym_key_click,
    STATE(7), 2,
      sym_fn_key,
      sym_special_key,
    STATE(13), 2,
      sym_modifier_key,
      aux_sym_report_repeat1,
    ACTIONS(19), 5,
      anon_sym_SHIFT,
      anon_sym_CARET,
      anon_sym_GUI,
      anon_sym_CTRL,
      anon_sym_ALT,
    ACTIONS(25), 10,
      anon_sym_SPACE,
      anon_sym__,
      anon_sym_UP,
      anon_sym_DOWN,
      anon_sym_LEFT,
      anon_sym_RIGHT,
      anon_sym_TAB,
      anon_sym_ESC,
      anon_sym_BACKSPACE,
      anon_sym_ENTER,
  [37] = 1,
    ACTIONS(46), 20,
      anon_sym_RPAREN,
      anon_sym_SERIAL_DEVICE,
      anon_sym_SHIFT,
      anon_sym_CARET,
      anon_sym_GUI,
      anon_sym_CTRL,
      anon_sym_ALT,
      sym_lowercase_key,
      anon_sym_FN,
      anon_sym_SPACE,
      anon_sym__,
      anon_sym_UP,
      anon_sym_DOWN,
      anon_sym_LEFT,
      anon_sym_RIGHT,
      anon_sym_TAB,
      anon_sym_ESC,
      anon_sym_BACKSPACE,
      anon_sym_ENTER,
      anon_sym_SAVE,
  [60] = 1,
    ACTIONS(48), 20,
      anon_sym_RPAREN,
      anon_sym_SERIAL_DEVICE,
      anon_sym_SHIFT,
      anon_sym_CARET,
      anon_sym_GUI,
      anon_sym_CTRL,
      anon_sym_ALT,
      sym_lowercase_key,
      anon_sym_FN,
      anon_sym_SPACE,
      anon_sym__,
      anon_sym_UP,
      anon_sym_DOWN,
      anon_sym_LEFT,
      anon_sym_RIGHT,
      anon_sym_TAB,
      anon_sym_ESC,
      anon_sym_BACKSPACE,
      anon_sym_ENTER,
      anon_sym_SAVE,
  [83] = 1,
    ACTIONS(50), 20,
      anon_sym_RPAREN,
      anon_sym_SERIAL_DEVICE,
      anon_sym_SHIFT,
      anon_sym_CARET,
      anon_sym_GUI,
      anon_sym_CTRL,
      anon_sym_ALT,
      sym_lowercase_key,
      anon_sym_FN,
      anon_sym_SPACE,
      anon_sym__,
      anon_sym_UP,
      anon_sym_DOWN,
      anon_sym_LEFT,
      anon_sym_RIGHT,
      anon_sym_TAB,
      anon_sym_ESC,
      anon_sym_BACKSPACE,
      anon_sym_ENTER,
      anon_sym_SAVE,
  [106] = 1,
    ACTIONS(52), 20,
      anon_sym_RPAREN,
      anon_sym_SERIAL_DEVICE,
      anon_sym_SHIFT,
      anon_sym_CARET,
      anon_sym_GUI,
      anon_sym_CTRL,
      anon_sym_ALT,
      sym_lowercase_key,
      anon_sym_FN,
      anon_sym_SPACE,
      anon_sym__,
      anon_sym_UP,
      anon_sym_DOWN,
      anon_sym_LEFT,
      anon_sym_RIGHT,
      anon_sym_TAB,
      anon_sym_ESC,
      anon_sym_BACKSPACE,
      anon_sym_ENTER,
      anon_sym_SAVE,
  [129] = 1,
    ACTIONS(54), 20,
      anon_sym_RPAREN,
      anon_sym_SERIAL_DEVICE,
      anon_sym_SHIFT,
      anon_sym_CARET,
      anon_sym_GUI,
      anon_sym_CTRL,
      anon_sym_ALT,
      sym_lowercase_key,
      anon_sym_FN,
      anon_sym_SPACE,
      anon_sym__,
      anon_sym_UP,
      anon_sym_DOWN,
      anon_sym_LEFT,
      anon_sym_RIGHT,
      anon_sym_TAB,
      anon_sym_ESC,
      anon_sym_BACKSPACE,
      anon_sym_ENTER,
      anon_sym_SAVE,
  [152] = 1,
    ACTIONS(56), 20,
      anon_sym_RPAREN,
      anon_sym_SERIAL_DEVICE,
      anon_sym_SHIFT,
      anon_sym_CARET,
      anon_sym_GUI,
      anon_sym_CTRL,
      anon_sym_ALT,
      sym_lowercase_key,
      anon_sym_FN,
      anon_sym_SPACE,
      anon_sym__,
      anon_sym_UP,
      anon_sym_DOWN,
      anon_sym_LEFT,
      anon_sym_RIGHT,
      anon_sym_TAB,
      anon_sym_ESC,
      anon_sym_BACKSPACE,
      anon_sym_ENTER,
      anon_sym_SAVE,
  [175] = 1,
    ACTIONS(58), 20,
      anon_sym_RPAREN,
      anon_sym_SERIAL_DEVICE,
      anon_sym_SHIFT,
      anon_sym_CARET,
      anon_sym_GUI,
      anon_sym_CTRL,
      anon_sym_ALT,
      sym_lowercase_key,
      anon_sym_FN,
      anon_sym_SPACE,
      anon_sym__,
      anon_sym_UP,
      anon_sym_DOWN,
      anon_sym_LEFT,
      anon_sym_RIGHT,
      anon_sym_TAB,
      anon_sym_ESC,
      anon_sym_BACKSPACE,
      anon_sym_ENTER,
      anon_sym_SAVE,
  [198] = 3,
    STATE(13), 2,
      sym_modifier_key,
      aux_sym_report_repeat1,
    ACTIONS(60), 5,
      anon_sym_SHIFT,
      anon_sym_CARET,
      anon_sym_GUI,
      anon_sym_CTRL,
      anon_sym_ALT,
    ACTIONS(63), 12,
      sym_lowercase_key,
      anon_sym_FN,
      anon_sym_SPACE,
      anon_sym__,
      anon_sym_UP,
      anon_sym_DOWN,
      anon_sym_LEFT,
      anon_sym_RIGHT,
      anon_sym_TAB,
      anon_sym_ESC,
      anon_sym_BACKSPACE,
      anon_sym_ENTER,
  [224] = 1,
    ACTIONS(65), 17,
      anon_sym_SHIFT,
      anon_sym_CARET,
      anon_sym_GUI,
      anon_sym_CTRL,
      anon_sym_ALT,
      sym_lowercase_key,
      anon_sym_FN,
      anon_sym_SPACE,
      anon_sym__,
      anon_sym_UP,
      anon_sym_DOWN,
      anon_sym_LEFT,
      anon_sym_RIGHT,
      anon_sym_TAB,
      anon_sym_ESC,
      anon_sym_BACKSPACE,
      anon_sym_ENTER,
  [244] = 8,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    ACTIONS(69), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(72), 1,
      anon_sym_DELAY,
    ACTIONS(75), 1,
      anon_sym_SCRIPT,
    ACTIONS(81), 1,
      anon_sym_SEND,
    ACTIONS(84), 2,
      anon_sym_SEND_FILE,
      anon_sym_STOP,
    ACTIONS(78), 3,
      anon_sym_SERIAL_DEVICE,
      anon_sym_INPUT_FILE,
      anon_sym_OUTPUT_FILE,
    STATE(15), 3,
      sym_comment,
      sym_command,
      aux_sym_source_file_repeat1,
  [274] = 8,
    ACTIONS(5), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(7), 1,
      anon_sym_DELAY,
    ACTIONS(9), 1,
      anon_sym_SCRIPT,
    ACTIONS(13), 1,
      anon_sym_SEND,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 2,
      anon_sym_SEND_FILE,
      anon_sym_STOP,
    ACTIONS(11), 3,
      anon_sym_SERIAL_DEVICE,
      anon_sym_INPUT_FILE,
      anon_sym_OUTPUT_FILE,
    STATE(15), 3,
      sym_comment,
      sym_command,
      aux_sym_source_file_repeat1,
  [304] = 2,
    ACTIONS(91), 1,
      anon_sym_SEND,
    ACTIONS(89), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN_STAR,
      anon_sym_DELAY,
      anon_sym_SCRIPT,
      anon_sym_SERIAL_DEVICE,
      anon_sym_INPUT_FILE,
      anon_sym_OUTPUT_FILE,
      anon_sym_SEND_FILE,
      anon_sym_STOP,
  [319] = 2,
    ACTIONS(95), 1,
      anon_sym_SEND,
    ACTIONS(93), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN_STAR,
      anon_sym_DELAY,
      anon_sym_SCRIPT,
      anon_sym_SERIAL_DEVICE,
      anon_sym_INPUT_FILE,
      anon_sym_OUTPUT_FILE,
      anon_sym_SEND_FILE,
      anon_sym_STOP,
  [334] = 2,
    ACTIONS(99), 1,
      anon_sym_SEND,
    ACTIONS(97), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN_STAR,
      anon_sym_DELAY,
      anon_sym_SCRIPT,
      anon_sym_SERIAL_DEVICE,
      anon_sym_INPUT_FILE,
      anon_sym_OUTPUT_FILE,
      anon_sym_SEND_FILE,
      anon_sym_STOP,
  [349] = 3,
    ACTIONS(101), 1,
      anon_sym_RPAREN,
    ACTIONS(103), 1,
      sym_lowercase_key,
    STATE(22), 1,
      aux_sym_generic_args_repeat1,
  [359] = 3,
    ACTIONS(105), 1,
      sym_lowercase_key,
    STATE(20), 1,
      aux_sym_generic_args_repeat1,
    STATE(33), 1,
      sym_generic_args,
  [369] = 3,
    ACTIONS(107), 1,
      anon_sym_RPAREN,
    ACTIONS(109), 1,
      sym_lowercase_key,
    STATE(22), 1,
      aux_sym_generic_args_repeat1,
  [379] = 1,
    ACTIONS(112), 1,
      anon_sym_LPAREN,
  [383] = 1,
    ACTIONS(114), 1,
      aux_sym_comment_token1,
  [387] = 1,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
  [391] = 1,
    ACTIONS(118), 1,
      sym_delay_args,
  [395] = 1,
    ACTIONS(120), 1,
      anon_sym_LPAREN,
  [399] = 1,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
  [403] = 1,
    ACTIONS(124), 1,
      anon_sym_STAR_RPAREN,
  [407] = 1,
    ACTIONS(126), 1,
      anon_sym_LPAREN,
  [411] = 1,
    ACTIONS(128), 1,
      anon_sym_RPAREN,
  [415] = 1,
    ACTIONS(130), 1,
      aux_sym_fn_key_token1,
  [419] = 1,
    ACTIONS(132), 1,
      anon_sym_RPAREN,
  [423] = 1,
    ACTIONS(134), 1,
      anon_sym_RPAREN,
  [427] = 1,
    ACTIONS(136), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 37,
  [SMALL_STATE(7)] = 60,
  [SMALL_STATE(8)] = 83,
  [SMALL_STATE(9)] = 106,
  [SMALL_STATE(10)] = 129,
  [SMALL_STATE(11)] = 152,
  [SMALL_STATE(12)] = 175,
  [SMALL_STATE(13)] = 198,
  [SMALL_STATE(14)] = 224,
  [SMALL_STATE(15)] = 244,
  [SMALL_STATE(16)] = 274,
  [SMALL_STATE(17)] = 304,
  [SMALL_STATE(18)] = 319,
  [SMALL_STATE(19)] = 334,
  [SMALL_STATE(20)] = 349,
  [SMALL_STATE(21)] = 359,
  [SMALL_STATE(22)] = 369,
  [SMALL_STATE(23)] = 379,
  [SMALL_STATE(24)] = 383,
  [SMALL_STATE(25)] = 387,
  [SMALL_STATE(26)] = 391,
  [SMALL_STATE(27)] = 395,
  [SMALL_STATE(28)] = 399,
  [SMALL_STATE(29)] = 403,
  [SMALL_STATE(30)] = 407,
  [SMALL_STATE(31)] = 411,
  [SMALL_STATE(32)] = 415,
  [SMALL_STATE(33)] = 419,
  [SMALL_STATE(34)] = 423,
  [SMALL_STATE(35)] = 427,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_script_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_script_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_script_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_script_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_script_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_script_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_click, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_report, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special_key, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_report, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_key, 4, 0, 0),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_report_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_report_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_modifier_key, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 4, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 4, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_args, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_generic_args_repeat1, 2, 0, 0),
  [109] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_generic_args_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [122] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_erpel_script(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "erpel_script",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
